# Numpy Basic assignment

# Consider the below code to answer further questions:
# import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [1]:
import numpy as np

In [2]:
list_=['1','2','3','4','5']

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list=np.array(object =list_)

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

# Answer-1-In this corrected code, we have used single quotes (' ') to properly represent strings in the list_. We then create a NumPy array, array_list, from this list. The data type of list_ is a Python list, and the data type of array_list is a NumPy array.

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

# Answer-2

In [8]:
for elem in list_:
    print(f"Data type of element in list_: {elem} - {type(elem)}")

for elem in array_list:
    print(f"Data type of element in array_list: {elem} - {type(elem)}")

Data type of element in list_: 1 - <class 'str'>
Data type of element in list_: 2 - <class 'str'>
Data type of element in list_: 3 - <class 'str'>
Data type of element in list_: 4 - <class 'str'>
Data type of element in list_: 5 - <class 'str'>
Data type of element in array_list: 1 - <class 'numpy.str_'>
Data type of element in array_list: 2 - <class 'numpy.str_'>
Data type of element in array_list: 3 - <class 'numpy.str_'>
Data type of element in array_list: 4 - <class 'numpy.str_'>
Data type of element in array_list: 5 - <class 'numpy.str_'>


# Question-3-Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Answer-3-

In [9]:
array_list = np.array(object = list_, dtype = int)

In [10]:
array_list

array([1, 2, 3, 4, 5])

In [11]:
for elem in list_:
    print(f"Data type of element in list_: {elem} - {type(elem)}")

for elem in array_list:
    print(f"Data type of element in array_list: {elem} - {type(elem)}")

Data type of element in list_: 1 - <class 'str'>
Data type of element in list_: 2 - <class 'str'>
Data type of element in list_: 3 - <class 'str'>
Data type of element in list_: 4 - <class 'str'>
Data type of element in list_: 5 - <class 'str'>
Data type of element in array_list: 1 - <class 'numpy.int64'>
Data type of element in array_list: 2 - <class 'numpy.int64'>
Data type of element in array_list: 3 - <class 'numpy.int64'>
Data type of element in array_list: 4 - <class 'numpy.int64'>
Data type of element in array_list: 5 - <class 'numpy.int64'>


# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [12]:
num_list =[[1,2,3],[4,5,6]]

In [13]:
num_array =np.array(object=num_list)

In [14]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [15]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) arr.shape
# (ii) arr.size

# Answer-4-

In [16]:
shape = num_array.shape

In [17]:
shape

(2, 3)

In [18]:
size = num_array.size

In [19]:
size

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).] # data=np.random.randint(0,1,(3,3))

# answer-5-

In [27]:
data=np.random.randint(0,1,(3,3))

In [28]:
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
data1=np.diag([1,1,1,1,1,]) for diagonal

# answer-6-

In [35]:
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [36]:
data1=np.diag([1,1,1,1,1,])

In [37]:
data1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Assignment Completed